### ISSUE TITLE
Script hangs at "Connected to Gitea, version..."

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [h44z/gitlab_to_gitea#5]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/7723097/82780491-8ce4dc00-9e81-11ea-8b18-8bf1466da399.png">

Any idea how to solve this?

**Comment by h44z** [comment]
are you using my custom version of pygitea (https://github.com/h44z/pygitea) ?

**Comment by Doko-Demo-Doa** [comment]
@h44z I followed your guide in README.md, which has `git+https://github.com/h44z/pygitea` in `requirements.txt`. Did I miss something?

**Comment by h44z** [comment]
@Doko-Demo-Doa if you followed the README you should be fine. I currently have no gitlab instance for testing, but I think the connection to gitlab is not working correctly as the script gets stuck while reading the gitlab users and groups.
Which gitlab version are you using?

**Comment by Doko-Demo-Doa** [comment]
@h44z I'm cloning right from `https://gitlab.com/` . They got an update recently, maybe that's the issue?

**Comment by h44z** [comment]
@Doko-Demo-Doa 
I think I now the source of the problem. Since you are trying to migrate from gitlab.com, the script queries ALL publicly visible users (I think every user on gitlab.com is publicly visible). According to wikipedia, gitlab.com has more than 100000 users. So I guess the script is not really hanging, it just takes time to load all records.

I don't have the time right now to implement a filter that fixes this problem, but as always, pull requests are welcome.

**Comment by Doko-Demo-Doa** [comment]
Alright thank you. I'm not familiar with Python but I will give it a try.
